package com.google.security.zynamics.bindiff.enums;

public enum EPlaceholderType
{
    MATCHED_ABOVE_INSTRUCTION_COMMENT("MATCHED_ABOVE_INSTRUCTION_COMMENT", 0), 
    MATCHED_BEHIND_INSTRUCTION_COMMENT("MATCHED_BEHIND_INSTRUCTION_COMMENT", 1), 
    UNMATCHED_ABOVE_INSTRUCTION_COMMENT("UNMATCHED_ABOVE_INSTRUCTION_COMMENT", 2), 
    UNMATCHED_INSTRUCTION("UNMATCHED_INSTRUCTION", 3), 
    UNMATCHED_BEHIND_INSTRUCTION_COMMENT("UNMATCHED_BEHIND_INSTRUCTION_COMMENT", 4), 
    BASICBLOCK_COMMENT("BASICBLOCK_COMMENT", 5);
    
    private EPlaceholderType(final String s, final int n) {
    }
}
